In [ ]:
import pandas as pd
import os
import json
import glob

In [ ]:
def get_files(filepath):
    all_files = []
    for root, dris, files in os.walk(filepath):
        files = glob.glob(os.path.join(root,'*.json'))
        for f in files:
            all_files.append(os.path.abspath(f))

    return all_files

In [ ]:
ipl_data = get_files("ipl_json")

In [ ]:
ipl_data[0]

In [ ]:
filepath = ipl_data[0]

In [ ]:
df = pd.read_json(filepath, lines = True)

In [ ]:
import os

print(f"File Size: {os.path.getsize(filepath)} bytes")

In [ ]:
df = pd.read_json(filepath, lines=True, encoding="utf-8")

In [ ]:
import chardet

In [ ]:
with open(filepath, 'rb') as f:
    result = chardet.detect(f.read(10000))  # Read first 10,000 bytes for detection
    print(result)

In [ ]:
import json

with open(filepath, 'r', encoding="utf-8") as f:
    data = f.read()
    print(data[:500])  # Print first 500 characters
    json_obj = json.loads(data)  # Check if it loads properly

In [ ]:
import json
import pandas as pd

with open(filepath, "r", encoding="utf-8") as f:
    data = json.load(f) 

df = pd.json_normalize(data)
print(df.head())

In [ ]:
ipl_list = []

for ipl_json in ipl_data:
    with open (ipl_json) as doc:
        exp = json.load(doc)
        ipl_list.append(exp)

In [ ]:
type(exp)

In [ ]:
exp

In [ ]:
q_a = exp['info']
q_a

In [ ]:
exp['innings']

In [ ]:
type(q_a)

In [ ]:
ipl_list[:2]

In [ ]:
df2 = pd.DataFrame(ipl_list)
df2

In [ ]:
ipl1 = exp['innings']

In [ ]:
ipl1

In [ ]:
for inning in ipl1:
    print(inning)

In [ ]:
type(inning)

In [ ]:
for over in overs:
    print(over)

In [62]:
ipl_list = []

for ipl_json in ipl_data:
    with open (ipl_json) as doc:
        exp = json.load(doc)
        ipl_list.append(exp)

In [64]:
inning = exp['innings']

In [66]:
inning

[{'team': 'Sunrisers Hyderabad',
  'overs': [{'over': 0,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}}]},
   {'over': 1,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'extras': {'wides': 2},
      'non_striker': 'S Dhawan',
      'runs': {'batter': 0, 'extras': 2, 'total': 2}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 2,
    'deliveries': [{'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}}]},
   {'over': 3,
    'deliveries': [{'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}}]},
   {'over': 4,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'SR Watson',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'DA Warner',
      'bowler': 'SR Watson',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'S Dhawan',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'SR Watson',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'SR Watson',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 5,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'extras': {'wides': 1},
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'S Dhawan',
      'bowler': 'CH Gayle',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'CH Gayle',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}}]},
   {'over': 6,
    'deliveries': [{'batter': 'S Dhawan',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'S Dhawan',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'S Dhawan',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 2, 'extras': 0, 'total': 2}},
     {'batter': 'S Dhawan',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'S Dhawan',
        'fielders': [{'name': 'CJ Jordan'}]}]},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'MC Henriques',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 7,
    'deliveries': [{'batter': 'MC Henriques',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DA Warner',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'DA Warner',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'MC Henriques',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'Iqbal Abdulla',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 8,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'MC Henriques',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 2, 'extras': 0, 'total': 2}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'extras': {'byes': 1},
      'non_striker': 'MC Henriques',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}}]},
   {'over': 9,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'MC Henriques',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'MC Henriques',
      'bowler': 'CJ Jordan',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'MC Henriques',
        'fielders': [{'name': 'YS Chahal'}]}]},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}}]},
   {'over': 10,
    'deliveries': [{'batter': 'Yuvraj Singh',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'SR Watson',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'SR Watson',
      'non_striker': 'DA Warner',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}}]},
   {'over': 11,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'extras': {'legbyes': 1},
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'CJ Jordan',
      'non_striker': 'DA Warner',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'CJ Jordan',
      'non_striker': 'DA Warner',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'CJ Jordan',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DA Warner',
      'bowler': 'CJ Jordan',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 12,
    'deliveries': [{'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'YS Chahal',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 13,
    'deliveries': [{'batter': 'Yuvraj Singh',
      'bowler': 'S Aravind',
      'non_striker': 'DA Warner',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'DA Warner',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'DA Warner',
        'fielders': [{'name': 'Iqbal Abdulla'}]}]},
     {'batter': 'DJ Hooda',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'S Aravind',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DJ Hooda',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}}]},
   {'over': 14,
    'deliveries': [{'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DJ Hooda',
      'bowler': 'YS Chahal',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'YS Chahal',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 15,
    'deliveries': [{'batter': 'Yuvraj Singh',
      'bowler': 'S Aravind',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'S Aravind',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DJ Hooda',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'DJ Hooda',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'S Aravind',
      'non_striker': 'DJ Hooda',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'DJ Hooda',
      'bowler': 'S Aravind',
      'non_striker': 'Yuvraj Singh',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'DJ Hooda',
        'fielders': [{'name': 'V Kohli'}]}]}]},
   {'over': 16,
    'deliveries': [{'batter': 'Yuvraj Singh',
      'bowler': 'CJ Jordan',
      'extras': {'wides': 1},
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'Yuvraj Singh',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'Yuvraj Singh',
        'fielders': [{'name': 'SR Watson'}]}]},
     {'batter': 'NV Ojha',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'NV Ojha',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'BCJ Cutting',
      'bowler': 'CJ Jordan',
      'extras': {'legbyes': 1},
      'non_striker': 'NV Ojha',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'NV Ojha',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'NV Ojha',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 2, 'extras': 0, 'total': 2}}]},
   {'over': 17,
    'deliveries': [{'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'extras': {'wides': 1},
      'non_striker': 'NV Ojha',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'extras': {'wides': 1},
      'non_striker': 'NV Ojha',
      'runs': {'batter': 0, 'extras': 1, 'total': 1}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'NV Ojha',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'run out',
        'player_out': 'NV Ojha',
        'fielders': [{'name': 'SR Watson'}]}]},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 0, 'extras': 0, 'total': 0}}]},
   {'over': 18,
    'deliveries': [{'batter': 'Bipul Sharma',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'BCJ Cutting',
      'bowler': 'CJ Jordan',
      'non_striker': 'Bipul Sharma',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}},
     {'batter': 'Bipul Sharma',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'Bipul Sharma',
      'bowler': 'CJ Jordan',
      'non_striker': 'BCJ Cutting',
      'runs': {'batter': 0, 'extras': 0, 'total': 0},
      'wickets': [{'kind': 'caught',
        'player_out': 'Bipul Sharma',
        'fielders': [{'name': 'YS Chahal'}]}]},
     {'batter': 'BCJ Cutting',
      'bowler': 'CJ Jordan',
      'extras': {'wides': 5},
      'non_striker': 'B Kumar',
      'runs': {'batter': 0, 'extras': 5, 'total': 5}},
     {'batter': 'BCJ Cutting',
      'bowler': 'CJ Jordan',
      'non_striker': 'B Kumar',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'BCJ Cutting',
      'bowler': 'CJ Jordan',
      'non_striker': 'B Kumar',
      'runs': {'batter': 1, 'extras': 0, 'total': 1}}]},
   {'over': 19,
    'deliveries': [{'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'B Kumar',
      'runs': {'batter': 4, 'extras': 0, 'total': 4}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'B Kumar',
      'runs': {'batter': 6, 'extras': 0, 'total': 6}},
     {'batter': 'BCJ Cutting',
      'bowler': 'SR Watson',
      'non_striker': 'B Kumar',

In [69]:
for inning_data in inning:
    print(inning_data)

{'team': 'Sunrisers Hyderabad', 'overs': [{'over': 0, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}, {'over': 1, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'CH Gayle', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'CH Gayle', 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DA Warner', 'bowler': 'CH Gayle', 'extras': {'wides': 2}, 'non_striker': 'S Dhawan', 'runs': {'batter': 0, 'extras': 2, 'total': 2}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 2, 'deliveries': [{'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'S Dhawan', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'S Dhawan', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}, {'over': 3, 'deliveries': [{'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'CH Gayle', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}, {'over': 4, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'SR Watson', 'non_striker': 'S Dhawan', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DA Warner', 'bowler': 'SR Watson', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'S Dhawan', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'SR Watson', 'non_striker': 'S Dhawan', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'SR Watson', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 5, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'CH Gayle', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'extras': {'wides': 1}, 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'S Dhawan', 'bowler': 'CH Gayle', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'CH Gayle', 'non_striker': 'S Dhawan', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}, {'over': 6, 'deliveries': [{'batter': 'S Dhawan', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'S Dhawan', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'S Dhawan', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'S Dhawan', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'S Dhawan', 'fielders': [{'name': 'CJ Jordan'}]}]}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'MC Henriques', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'MC Henriques', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 7, 'deliveries': [{'batter': 'MC Henriques', 'bowler': 'Iqbal Abdulla', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'Iqbal Abdulla', 'non_striker': 'MC Henriques', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DA Warner', 'bowler': 'Iqbal Abdulla', 'non_striker': 'MC Henriques', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'DA Warner', 'bowler': 'Iqbal Abdulla', 'non_striker': 'MC Henriques', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'MC Henriques', 'bowler': 'Iqbal Abdulla', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'Iqbal Abdulla', 'non_striker': 'MC Henriques', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 8, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'MC Henriques', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'MC Henriques', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'MC Henriques', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'MC Henriques', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'MC Henriques', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'extras': {'byes': 1}, 'non_striker': 'MC Henriques', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}]}, {'over': 9, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'MC Henriques', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'MC Henriques', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'MC Henriques', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'MC Henriques', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'MC Henriques', 'bowler': 'CJ Jordan', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'MC Henriques', 'fielders': [{'name': 'YS Chahal'}]}]}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}, {'over': 10, 'deliveries': [{'batter': 'Yuvraj Singh', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'SR Watson', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'SR Watson', 'non_striker': 'DA Warner', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}, {'over': 11, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'extras': {'legbyes': 1}, 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'CJ Jordan', 'non_striker': 'DA Warner', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'Yuvraj Singh', 'bowler': 'CJ Jordan', 'non_striker': 'DA Warner', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'Yuvraj Singh', 'bowler': 'CJ Jordan', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DA Warner', 'bowler': 'CJ Jordan', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 12, 'deliveries': [{'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'YS Chahal', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 13, 'deliveries': [{'batter': 'Yuvraj Singh', 'bowler': 'S Aravind', 'non_striker': 'DA Warner', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'DA Warner', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'DA Warner', 'fielders': [{'name': 'Iqbal Abdulla'}]}]}, {'batter': 'DJ Hooda', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'S Aravind', 'non_striker': 'DJ Hooda', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DJ Hooda', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}, {'over': 14, 'deliveries': [{'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DJ Hooda', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DJ Hooda', 'bowler': 'YS Chahal', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DJ Hooda', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DJ Hooda', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DJ Hooda', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Yuvraj Singh', 'bowler': 'YS Chahal', 'non_striker': 'DJ Hooda', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 15, 'deliveries': [{'batter': 'Yuvraj Singh', 'bowler': 'S Aravind', 'non_striker': 'DJ Hooda', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'Yuvraj Singh', 'bowler': 'S Aravind', 'non_striker': 'DJ Hooda', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DJ Hooda', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'DJ Hooda', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'S Aravind', 'non_striker': 'DJ Hooda', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'DJ Hooda', 'bowler': 'S Aravind', 'non_striker': 'Yuvraj Singh', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'DJ Hooda', 'fielders': [{'name': 'V Kohli'}]}]}]}, {'over': 16, 'deliveries': [{'batter': 'Yuvraj Singh', 'bowler': 'CJ Jordan', 'extras': {'wides': 1}, 'non_striker': 'BCJ Cutting', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'Yuvraj Singh', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'Yuvraj Singh', 'fielders': [{'name': 'SR Watson'}]}]}, {'batter': 'NV Ojha', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'NV Ojha', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'BCJ Cutting', 'bowler': 'CJ Jordan', 'extras': {'legbyes': 1}, 'non_striker': 'NV Ojha', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'NV Ojha', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'NV Ojha', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}]}, {'over': 17, 'deliveries': [{'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'extras': {'wides': 1}, 'non_striker': 'NV Ojha', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'extras': {'wides': 1}, 'non_striker': 'NV Ojha', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'NV Ojha', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'run out', 'player_out': 'NV Ojha', 'fielders': [{'name': 'SR Watson'}]}]}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}, {'over': 18, 'deliveries': [{'batter': 'Bipul Sharma', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'BCJ Cutting', 'bowler': 'CJ Jordan', 'non_striker': 'Bipul Sharma', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Bipul Sharma', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'Bipul Sharma', 'bowler': 'CJ Jordan', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'Bipul Sharma', 'fielders': [{'name': 'YS Chahal'}]}]}, {'batter': 'BCJ Cutting', 'bowler': 'CJ Jordan', 'extras': {'wides': 5}, 'non_striker': 'B Kumar', 'runs': {'batter': 0, 'extras': 5, 'total': 5}}, {'batter': 'BCJ Cutting', 'bowler': 'CJ Jordan', 'non_striker': 'B Kumar', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'BCJ Cutting', 'bowler': 'CJ Jordan', 'non_striker': 'B Kumar', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}, {'over': 19, 'deliveries': [{'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'B Kumar', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'B Kumar', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'B Kumar', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'B Kumar', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'B Kumar', 'bowler': 'SR Watson', 'non_striker': 'BCJ Cutting', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'BCJ Cutting', 'bowler': 'SR Watson', 'non_striker': 'B Kumar', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}], 'powerplays': [{'from': 0.1, 'to': 5.7, 'type': 'mandatory'}]}

In [70]:
type(inning_data)

dict

In [71]:
over = inning_data['overs']

In [ ]:
over

In [75]:
for over_data in over:
    print(over_data)

{'over': 0, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'B Kumar', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'B Kumar', 'extras': {'legbyes': 1}, 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'non_striker': 'CH Gayle', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 1, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'BB Sran', 'extras': {'wides': 1}, 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'extras': {'wides': 1}, 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 2, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'B Kumar', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'B Kumar', 'extras': {'legbyes': 1}, 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'extras': {'wides': 1}, 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'B Kumar', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'B Kumar', 'non_striker': 'V Kohli', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'CH Gayle', 'bowler': 'B Kumar', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'B Kumar', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 3, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'CH Gayle', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 4, 'deliveries': [{'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 5, 'deliveries': [{'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'Mustafizur Rahman', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'Mustafizur Rahman', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}]}
{'over': 6, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'MC Henriques', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'MC Henriques', 'non_striker': 'CH Gayle', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'V Kohli', 'bowler': 'MC Henriques', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 7, 'deliveries': [{'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'extras': {'wides': 1}, 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 8, 'deliveries': [{'batter': 'V Kohli', 'bowler': 'MC Henriques', 'non_striker': 'CH Gayle', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'V Kohli', 'bowler': 'MC Henriques', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'CH Gayle', 'bowler': 'MC Henriques', 'non_striker': 'V Kohli', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 9, 'deliveries': [{'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'Mustafizur Rahman', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CH Gayle', 'bowler': 'Mustafizur Rahman', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CH Gayle', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 10, 'deliveries': [{'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'CH Gayle', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'CH Gayle', 'bowler': 'BCJ Cutting', 'non_striker': 'V Kohli', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'CH Gayle', 'fielders': [{'name': 'Bipul Sharma'}]}]}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'AB de Villiers', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'AB de Villiers', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'V Kohli', 'bowler': 'BCJ Cutting', 'non_striker': 'AB de Villiers', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 11, 'deliveries': [{'batter': 'AB de Villiers', 'bowler': 'Bipul Sharma', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'V Kohli', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AB de Villiers', 'bowler': 'Bipul Sharma', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AB de Villiers', 'bowler': 'Bipul Sharma', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 12, 'deliveries': [{'batter': 'AB de Villiers', 'bowler': 'BB Sran', 'non_striker': 'V Kohli', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'V Kohli', 'bowler': 'BB Sran', 'non_striker': 'AB de Villiers', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'V Kohli', 'bowler': 'BB Sran', 'non_striker': 'AB de Villiers', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'V Kohli', 'bowler': 'BB Sran', 'non_striker': 'AB de Villiers', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'V Kohli', 'bowler': 'BB Sran', 'non_striker': 'AB de Villiers', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'bowled', 'player_out': 'V Kohli'}]}, {'batter': 'KL Rahul', 'bowler': 'BB Sran', 'non_striker': 'AB de Villiers', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 13, 'deliveries': [{'batter': 'KL Rahul', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}, {'batter': 'KL Rahul', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AB de Villiers', 'bowler': 'Bipul Sharma', 'non_striker': 'KL Rahul', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'KL Rahul', 'bowler': 'Bipul Sharma', 'non_striker': 'AB de Villiers', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'AB de Villiers', 'bowler': 'Bipul Sharma', 'non_striker': 'KL Rahul', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'AB de Villiers', 'fielders': [{'name': 'MC Henriques'}]}]}, {'batter': 'KL Rahul', 'bowler': 'Bipul Sharma', 'non_striker': 'SR Watson', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 14, 'deliveries': [{'batter': 'KL Rahul', 'bowler': 'MC Henriques', 'non_striker': 'SR Watson', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'SR Watson', 'bowler': 'MC Henriques', 'non_striker': 'KL Rahul', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'KL Rahul', 'bowler': 'MC Henriques', 'non_striker': 'SR Watson', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'SR Watson', 'bowler': 'MC Henriques', 'non_striker': 'KL Rahul', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'SR Watson', 'bowler': 'MC Henriques', 'non_striker': 'KL Rahul', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'SR Watson', 'bowler': 'MC Henriques', 'non_striker': 'KL Rahul', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}]}
{'over': 15, 'deliveries': [{'batter': 'KL Rahul', 'bowler': 'BCJ Cutting', 'non_striker': 'SR Watson', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'SR Watson', 'bowler': 'BCJ Cutting', 'non_striker': 'KL Rahul', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'KL Rahul', 'bowler': 'BCJ Cutting', 'non_striker': 'SR Watson', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'bowled', 'player_out': 'KL Rahul'}]}, {'batter': 'Sachin Baby', 'bowler': 'BCJ Cutting', 'non_striker': 'SR Watson', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'Sachin Baby', 'bowler': 'BCJ Cutting', 'non_striker': 'SR Watson', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'SR Watson', 'bowler': 'BCJ Cutting', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 16, 'deliveries': [{'batter': 'SR Watson', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'SR Watson', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'SR Watson', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'caught', 'player_out': 'SR Watson', 'fielders': [{'name': 'MC Henriques'}]}]}, {'batter': 'Sachin Baby', 'bowler': 'Mustafizur Rahman', 'non_striker': 'STR Binny', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'STR Binny', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}, {'batter': 'STR Binny', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}]}
{'over': 17, 'deliveries': [{'batter': 'STR Binny', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'STR Binny', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'STR Binny', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'STR Binny', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'STR Binny', 'bowler': 'B Kumar', 'extras': {'legbyes': 1}, 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'STR Binny', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}
{'over': 18, 'deliveries': [{'batter': 'STR Binny', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}, 'wickets': [{'kind': 'run out', 'player_out': 'STR Binny', 'fielders': [{'name': 'DJ Hooda'}, {'name': 'NV Ojha'}]}]}, {'batter': 'CJ Jordan', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'CJ Jordan', 'bowler': 'Mustafizur Rahman', 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 0, 'total': 0}}, {'batter': 'CJ Jordan', 'bowler': 'Mustafizur Rahman', 'extras': {'legbyes': 1}, 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'Sachin Baby', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CJ Jordan', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'Sachin Baby', 'bowler': 'Mustafizur Rahman', 'non_striker': 'CJ Jordan', 'runs': {'batter': 6, 'extras': 0, 'total': 6}}]}
{'over': 19, 'deliveries': [{'batter': 'CJ Jordan', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'CJ Jordan', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}, {'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'CJ Jordan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'run out', 'player_out': 'CJ Jordan', 'fielders': [{'name': 'NV Ojha'}]}]}, {'batter': 'Iqbal Abdulla', 'bowler': 'B Kumar', 'extras': {'legbyes': 1}, 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}, {'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'Iqbal Abdulla', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}, {'batter': 'Iqbal Abdulla', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}]}

In [ ]:
delivery = over_data['deliveries']

TypeError: list indices must be integers or slices, not str

In [77]:
delivery

[{'batter': 'CJ Jordan',
  'bowler': 'B Kumar',
  'non_striker': 'Sachin Baby',
  'runs': {'batter': 1, 'extras': 0, 'total': 1}},
 {'batter': 'Sachin Baby',
  'bowler': 'B Kumar',
  'non_striker': 'CJ Jordan',
  'runs': {'batter': 2, 'extras': 0, 'total': 2}},
 {'batter': 'Sachin Baby',
  'bowler': 'B Kumar',
  'non_striker': 'CJ Jordan',
  'runs': {'batter': 0, 'extras': 0, 'total': 0},
  'wickets': [{'kind': 'run out',
    'player_out': 'CJ Jordan',
    'fielders': [{'name': 'NV Ojha'}]}]},
 {'batter': 'Iqbal Abdulla',
  'bowler': 'B Kumar',
  'extras': {'legbyes': 1},
  'non_striker': 'Sachin Baby',
  'runs': {'batter': 0, 'extras': 1, 'total': 1}},
 {'batter': 'Sachin Baby',
  'bowler': 'B Kumar',
  'non_striker': 'Iqbal Abdulla',
  'runs': {'batter': 1, 'extras': 0, 'total': 1}},
 {'batter': 'Iqbal Abdulla',
  'bowler': 'B Kumar',
  'non_striker': 'Sachin Baby',
  'runs': {'batter': 4, 'extras': 0, 'total': 4}}]

In [78]:
for delivery_data in delivery:
    print(delivery_data)

{'batter': 'CJ Jordan', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}
{'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'CJ Jordan', 'runs': {'batter': 2, 'extras': 0, 'total': 2}}
{'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'CJ Jordan', 'runs': {'batter': 0, 'extras': 0, 'total': 0}, 'wickets': [{'kind': 'run out', 'player_out': 'CJ Jordan', 'fielders': [{'name': 'NV Ojha'}]}]}
{'batter': 'Iqbal Abdulla', 'bowler': 'B Kumar', 'extras': {'legbyes': 1}, 'non_striker': 'Sachin Baby', 'runs': {'batter': 0, 'extras': 1, 'total': 1}}
{'batter': 'Sachin Baby', 'bowler': 'B Kumar', 'non_striker': 'Iqbal Abdulla', 'runs': {'batter': 1, 'extras': 0, 'total': 1}}
{'batter': 'Iqbal Abdulla', 'bowler': 'B Kumar', 'non_striker': 'Sachin Baby', 'runs': {'batter': 4, 'extras': 0, 'total': 4}}

In [87]:
batter_name = delivery_data['batter']

In [88]:
batter_name

'Iqbal Abdulla'

In [99]:
def get_over_data():
    inning = exp['innings']
    get_data = []
    for inning_data in inning:
        over = inning_data['overs']
        for over_data in over:
            delivery = over_data['deliveries']
            get_data.append(delivery)

In [103]:
get_over_data()

In [104]:
with open('over_detail.json', 'w') as file:
    json.dump(get_data , file)

In [105]:
df5 = pd.DataFrame(get_data)
df5

Empty DataFrame
Columns: []
Index: []

In [101]:
df5

Empty DataFrame
Columns: []
Index: []

In [106]:
import pandas as pd

def get_over_data():
    innings = exp['innings']
    deliveries_list = []
    
    for inning_data in innings:
        inning_name = inning_data.get('team', 'Unknown Team')  # Get team name for context
        overs = inning_data.get('overs', [])
        
        for over_data in overs:
            over_number = over_data.get('over', None)  # Extract over number
            deliveries = over_data.get('deliveries', [])
            
            for delivery in deliveries:
                delivery['inning'] = inning_name
                delivery['over'] = over_number
                deliveries_list.append(delivery)  # Add each delivery as a row

    return pd.DataFrame(deliveries_list)  # Convert list of dicts to DataFrame

df = get_over_data()
print(df.head())  # Display first few rows

      batter     bowler non_striker                                    runs  \
0  DA Warner  S Aravind    S Dhawan  {'batter': 1, 'extras': 0, 'total': 1}
1   S Dhawan  S Aravind   DA Warner  {'batter': 1, 'extras': 0, 'total': 1}
2  DA Warner  S Aravind    S Dhawan  {'batter': 0, 'extras': 0, 'total': 0}
3  DA Warner  S Aravind    S Dhawan  {'batter': 1, 'extras': 0, 'total': 1}
4   S Dhawan  S Aravind   DA Warner  {'batter': 0, 'extras': 0, 'total': 0}

                inning  over extras wickets
0  Sunrisers Hyderabad     0    NaN     NaN
1  Sunrisers Hyderabad     0    NaN     NaN
2  Sunrisers Hyderabad     0    NaN     NaN
3  Sunrisers Hyderabad     0    NaN     NaN
4  Sunrisers Hyderabad     0    NaN     NaN

In [107]:
import pandas as pd

def get_over_data():
    innings = exp['innings']
    deliveries_list = []
    
    for inning_data in innings:
        inning_name = inning_data.get('team', 'Unknown Team')  # Get team name for context
        overs = inning_data.get('overs', [])
        
        for over_data in overs:
            over_number = over_data.get('over', None)  # Extract over number
            deliveries = over_data.get('deliveries', [])
            
            for delivery in deliveries:
                delivery['inning'] = inning_name
                delivery['over'] = over_number
                
                # Extract run details if available
                runs = delivery.get('runs', {})
                delivery['runs_batter'] = runs.get('batter', 0)
                delivery['runs_extras'] = runs.get('extras', 0)
                delivery['runs_total'] = runs.get('total', 0)
                
                deliveries_list.append(delivery)  # Add each delivery as a row

    # Convert to DataFrame and drop the original 'runs' column
    df = pd.DataFrame(deliveries_list).drop(columns=['runs'], errors='ignore')

    return df  

df = get_over_data()
print(df.head())  # Display first few rows

      batter     bowler non_striker               inning  over  runs_batter  \
0  DA Warner  S Aravind    S Dhawan  Sunrisers Hyderabad     0            1
1   S Dhawan  S Aravind   DA Warner  Sunrisers Hyderabad     0            1
2  DA Warner  S Aravind    S Dhawan  Sunrisers Hyderabad     0            0
3  DA Warner  S Aravind    S Dhawan  Sunrisers Hyderabad     0            1
4   S Dhawan  S Aravind   DA Warner  Sunrisers Hyderabad     0            0

   runs_extras  runs_total extras wickets
0            0           1    NaN     NaN
1            0           1    NaN     NaN
2            0           0    NaN     NaN
3            0           1    NaN     NaN
4            0           0    NaN     NaN

In [109]:
# def get_over_data():
#     innings = exp['innings']
#     deliveries_list = []
    
#     for inning_data in innings:
#         inning_name = inning_data.get('team', 'Unknown Team')
#         overs = inning_data.get('overs', [])
        
#         for over_data in overs:
#             over_number = over_data.get('over', None)
#             deliveries = over_data.get('deliveries', [])
            
#             for delivery in deliveries:
#                 delivery['inning'] = inning_name
#                 delivery['over'] = over_number
                
#                 runs = delivery.get('runs', {})
#                 delivery['runs_batter'] = runs.get('batter', 0)
#                 delivery['runs_extras'] = runs.get('extras', 0)
#                 delivery['runs_total'] = runs.get('total', 0)
                
#                 deliveries_list.append(delivery)

#     df = pd.DataFrame(deliveries_list).drop(columns=['runs'], errors='ignore')

#     return df

In [110]:
#df = get_over_data()

In [111]:
#df